local commands = require("slime_peek.commands")

describe("get_r_command", function()
    it("returns correct string for 'head'", function()
        assert.equal("head(content)\\n", commands.get_r_command("head", "content"))
    end)
    it("returns correct string for 'tail'", function()
        assert.equal("tail(content)\\n", commands.get_r_command("tail", "content"))
    end)
    it("returns correct string for 'names'", function()
        assert.equal("names(content)\\n", commands.get_r_command("names", "content"))
    end)
    it("returns correct string for 'dim'", function()
        assert.equal("dim(content)\\n", commands.get_r_command("dim", "content"))
    end)
    it("returns correct string for 'dtypes'", function()
        assert.equal("sapply(content, class)\\n", commands.get_r_command("dtypes", "content"))
    end)
    it("returns correct string for 'help'", function()
        assert.equal("help(content)\\n", commands.get_r_command("help", "content"))
    end)
end)

describe("get_python_command", function()
    it("returns correct string for 'head'", function()
        assert.equal("content.head()\\n", commands.get_python_command("head", "content"))
    end)
    it("returns correct string for 'tail'", function()
        assert.equal("content.tail()\\n", commands.get_python_command("tail", "content"))
    end)
    it("returns correct string for 'names'", function()
        assert.equal("content.columns.tolist()\\n", commands.get_python_command("names", "content"))
    end)
    it("returns correct string for 'dim'", function()
        assert.equal("content.shape\\n", commands.get_python_command("dim", "content"))
    end)
    it("returns correct string for 'dtypes'", function()
        assert.equal("content.dtypes\\n", commands.get_python_command("dtypes", "content"))
    end)
    it("returns correct string for 'help'", function()
        assert.equal("help(content)\\n", commands.get_python_command("help", "content"))
    end)
end)

describe("get_julia_command", function()
    it("returns correct string for 'head'", function()
        assert.equal("first(content, 5)\\n", commands.get_julia_command("head", "content"))
    end)
    it("returns correct string for 'tail'", function()
        assert.equal("last(content, 5)\\n", commands.get_julia_command("tail", "content"))
    end)
    it("returns correct string for 'names'", function()
        assert.equal("names(content)\\n", commands.get_julia_command("names", "content"))
    end)
    it("returns correct string for 'dim'", function()
        assert.equal("size(content)\\n", commands.get_julia_command("dim", "content"))
    end)
    it("returns correct string for 'dtypes'", function()
        assert.equal("eltype.(eachcol(content))\\n", commands.get_julia_command("dtypes", "content"))
    end)
    it("returns correct string for 'help'", function()
        assert.equal("@doc content\\n", commands.get_julia_command("help", "content"))
    end)
end)
